config/routes.rb
Rails.application.routes.draw do
  root to: 'brands#index'

  resources :brands do
    member do
      get 'relations'
    end
    resources :locations, except: :index
    resources :menu_items, except: :index
    resources :order_types, except: :index
    resources :price_levels, except: :index
  end

  resources :price_calculation, only: [:new, :create]

  resources :locations, only: [] do
    resources :day_parts
  end
end

app/models/brand.rb
class Brand
  include Mongoid::Document
  field :name, type: String

  has_many :locations, dependent: :destroy
  has_many :menu_items, dependent: :destroy
  has_many :order_types, dependent: :destroy
  has_many :price_levels, dependent: :destroy

  validates :name, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :relations, :edit, :update, :destroy]

  def index
    @brands = Brand.all
  end

  def show
  end

  def relations
    locations = @brand.locations
    render json: {
      locations: present_relations(locations),
      order_types: present_relations(@brand.order_types),
      menu_items: present_relations(@brand.menu_items),
      day_parts: present_relations(locations.first.day_parts)
    }
  end

  def new
    @brand = Brand.new
  end

  def edit
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to @brand, notice: 'Brand was successfully created.'
    else
      render :new
    end
  end

  def update
    if @brand.update(brand_params)
      redirect_to @brand, notice: 'Brand was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @brand.destroy
    redirect_to brands_url, notice: 'Brand was successfully destroyed.'
  end

  private
    def set_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(:name)
    end

    def present_relations(relations)
      relations.map do |relation|
        {
          _id: relation.id,
          name: relation.name
        }
      end
    end
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Brands</strong></div>
  <table class="table">
    <tr>
      <th>Name</th>
    </tr>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to brand.name, brand %></td>
        <td align="right"><%= edit_link(edit_brand_path(brand)) %> <%= destroy_link(brand) %></td>
      </tr>
    <% end %>
  </table>
  <div class="panel-footer"><%= link_to 'New Brand', new_brand_path %></div>
</div>

<%= link_to 'New Price Calculation', new_price_calculation_path, class: 'btn btn-success' %><br>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Destroy', brand_path(@brand), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', brands_path %>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Locations</strong></div>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Address</th>
    </tr>
    <% @brand.locations.each do |location| %>
      <tr>
        <td><%= link_to location.name, brand_location_path(@brand, location) %></td>
        <td><%= location.address %></td>
        <td align="right"><%= edit_link(edit_brand_location_path(@brand, location)) %> <%= destroy_link(brand_location_path(@brand, location)) %></td>
      </tr>
    <% end %>
  </table>
  <div class="panel-footer"><%= link_to 'New Location', new_brand_location_path(@brand) %></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Menu Items</strong></div>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>
    <% @brand.menu_items.each do |menu_item| %>
      <tr>
        <td><%= link_to menu_item.name, brand_menu_item_path(@brand, menu_item) %></td>
        <td><%= menu_item.description %>
        <td align="right"><%= edit_link(edit_brand_menu_item_path(@brand, menu_item)) %> <%= destroy_link(brand_menu_item_path(@brand, menu_item)) %></td>
      </tr>
    <% end %>
  </table>
  <div class="panel-footer"><%= link_to 'New Menu Item', new_brand_menu_item_path(@brand) %></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Order Types</strong></div>
  <table class="table">
    <tr>
      <th>Name</th>
    </tr>
    <% @brand.order_types.each do |order_type| %>
      <tr>
        <td><%= link_to order_type.name, brand_order_type_path(@brand, order_type) %></td>
        <td align="right"><%= edit_link(edit_brand_order_type_path(@brand, order_type)) %> <%= destroy_link(brand_order_type_path(@brand, order_type)) %></td>
      </tr>
    <% end %>
  </table>
  <div class="panel-footer"><%= link_to 'New Order Type', new_brand_order_type_path(@brand) %></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Price Levels</strong></div>
  <table class="table">
    <tr>
      <th>Name</th>
    </tr>
    <% @brand.price_levels.each do |price_level| %>
      <tr>
        <td><%= link_to price_level.name, brand_price_level_path(@brand, price_level) %></td>
        <td align="right"><%= edit_link(edit_brand_price_level_path(@brand, price_level)) %> <%= destroy_link(brand_price_level_path(@brand, price_level)) %></td>
      </tr>
    <% end %>
  </table>
  <div class="panel-footer"><%= link_to 'New Price Level', new_brand_price_level_path(@brand) %></div>
</div>