config/routes.rb
Rails.application.routes.draw do
  root to: 'brands#index'

  resources :brands do
    member do
      get 'relations'
    end
    resources :locations, except: :index
    resources :menu_items, except: :index
    resources :order_types, except: :index
    resources :price_levels, except: :index
  end

  resources :price_calculation, only: [:new, :create]

  resources :locations, only: [] do
    resources :day_parts
  end
end

app/models/location.rb
class Location
  include Mongoid::Document
  field :name, type: String
  field :address, type: String

  belongs_to :brand
  has_many :day_parts, dependent: :destroy
  embeds_many :price_level_associations

  accepts_nested_attributes_for :price_level_associations, allow_destroy: true, reject_if: :all_blank

  validates :brand, presence: true
  validates :name, presence: true

  # price_level_associations: [
  #   {
  #     order_type: 1,
  #     day_part: 1,
  #     price_level: 2
  #   },
  #   {
  #     order_type: 2,
  #     day_part: 2,
  #     price_level: 1
  #   },
  #   {
  #     order_type: 2,
  #     price_level: 1
  #   }
  # ]
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_brand

  def show
    @location = @brand.locations.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def edit
    @location = @brand.locations.find(params[:id])
  end

  def create
    @location = @brand.locations.new(location_params)
    if @location.save
      redirect_to brand_path(@brand), notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  def update
    @location = @brand.locations.find(params[:id])
    if @location.update(location_params)
      redirect_to brand_path(@brand), notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    location = @brand.locations.find(params[:id])
    location.destroy
    redirect_to brand_path(@brand)
  end

  private
    def set_brand
      @brand = Brand.find(params[:brand_id])
    end

    def location_params
      params.require(:location).permit(:name, :address, price_level_associations_attributes: [:id, :order_type_id, :day_part_id, :price_level_id, :_destroy])
    end
end

app/views/locations/_form.html.erb
<p>
  <strong>Brand:</strong>
  <%= @brand.name %>
</p>

<%= form_for [@brand, @location] do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="input-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="input-group">
    <%= f.fields_for :price_level_associations do |pla| %>
      <%= render 'price_level_association_fields', f: pla %>
    <% end %>
    <span class="links">
      <%= link_to_add_association 'add price level association', f, :price_level_associations, class: 'btn btn-sm btn-success' %>
    </span>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/locations/_price_level_association_fields.html.erb
<div class="nested-fields">
  <div class="input-group">
    <%= f.label :price_level_id %>
    <%= f.select :price_level_id, @brand.price_levels.map { |pl| [pl.name, pl.id] } %>
    <%= f.label :order_type_id %>
    <%= f.select :order_type_id, @brand.order_types.map { |ot| [ot.name, ot.id] } %>
    <%= f.label :day_part_id %>
    <%= f.select :day_part_id, @location.day_parts.map { |dp| [dp.name, dp.id] }, { include_blank: 'none'} %>
    <%= link_to_remove_association 'remove price level association', f, class: 'btn btn-sm btn-danger' %>
  </div>
</div>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', brand_location_path(@brand, @location) %> |
<%= link_to 'Back', brand_path(@brand) %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path(@brand) %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Price Level Associations</strong></div>
  <table class="table">
    <tr>
      <th>Price Level</th>
      <th>Order Type</th>
      <th>Day Part</th>
    </tr>
    <% @location.price_level_associations.includes(:price_level, :order_type, :day_part).each do |pla| %>
      <tr>
        <td><%= pla.price_level.name %></td>
        <td><%= pla.order_type.name %></td>
        <td><%= pla.day_part.try(:name) || '' %></td>
      <tr>
    <% end %>
  </table>
</div>

<%= link_to 'Edit', edit_brand_location_path(@brand, @location) %> |
<%= link_to 'Back', brand_path(@brand) %>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Day Parts</strong></div>
  <table class="table">
    <tr>
      <th>Name</th>
    </tr>
    <% @location.day_parts.each do |day_part| %>
      <tr>
        <td><%= link_to day_part.name, location_day_part_path(@location, day_part) %></td>
        <td align="right"><%= edit_link(edit_location_day_part_path(@location, day_part)) %> <%= destroy_link(location_day_part_path(@location, day_part)) %></td>
      </tr>
    <% end %>
  </table>
  <div class="panel-footer"><%= link_to 'New Day Part', new_location_day_part_path(@location) %></div>
</div>